global:
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key
  crAdoption: true

ibmLicensing:
  namespace: ibm-licensing
  # image registry namespace for cpfs utils image used in clean-job
  imageRegistry: cpopen/cpfs
  # imagePullPrefix can be specified for ibmUsageMetering to override the value at .global
  imagePullPrefix: icr.io