apiVersion: v2
name: ibm-licensing-cluster-scoped
description: A Helm chart for IBM License Service installation
type: application
<<<<<<< HEAD
version: 4.2.19
=======
version: 4.2.18
>>>>>>> latest-4.x
