global:
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key
  licenseAccept: true

ibmLicensing:
  namespace: ibm-licensing
  watchNamespace: ibm-licensing
  imageRegistryNamespaceOperator: cpopen
  imageRegistryNamespaceOperand: cpopen/cpfs
  spec:
<<<<<<< HEAD
    version: 4.2.19
=======
    version: 4.2.18
>>>>>>> latest-4.x
    datasource: datacollector
    httpsEnable: true
