apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicensing
metadata:
  name: instance
spec:
  apiSecretToken: ibm-licensing-token
  datasource: metering
  httpsEnable: true
  instanceNamespace: ibm-common-services
  imageRegistry: quay.io/opencloudio