apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicensing
metadata:
  name: example-ibmlicensing
spec:
  # Add fields here
  apiSecretToken: ibm-licensing-token
  datasource: datacollector
  httpsCertsSource: self-signed
  httpsEnable: false
  imageRegistry: quay.io/opencloudio/ibm-licensing
  imageTagPostfix: 1.0.0
  logLevel: INFO
  operatorVersion: v1.0
  apiNamespace: kube-system