apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Seamless Upgrades
    categories: Monitoring
    certified: "false"
    containerImage: icr.io/cpopen/ibm-licensing-operator:1.20.12
    createdAt: "2020-06-22T10:22:31Z"
    description: The IBM Licensing Operator provides a Kubernetes CRD-Based API to
      monitor the license usage of products.
    olm.skipRange: '>=1.0.0 <1.20.12'
    operators.operatorframework.io/builder: operator-sdk-v1.25.2
    operators.operatorframework.io/internal-objects: '["ibmlicensingmetadatas.operator.ibm.com",
      "ibmlicensingdefinitions.operator.ibm.com", "ibmlicensingquerysources.operator.ibm.com"]'
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
    operatorframework.io/os.linux: supported
  name: ibm-licensing-operator.v0.0.0
  namespace: ibm-common-services
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: 'IBMLicenseServiceReporter is the Schema for the ibmlicenseservicereporters
        API. Documentation For additional details regarding install parameters check:
        https://ibm.biz/icpfs39install. License By installing this product you accept
        the license terms https://ibm.biz/icpfs39license.'
      displayName: IBMLicense Service Reporter
      kind: IBMLicenseServiceReporter
      name: ibmlicenseservicereporters.operator.ibm.com
      specDescriptors:
      - description: Environment variable setting
        displayName: Environment variable setting
        path: envVariable
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      version: v1alpha1
    - description: 'IBM License Service is the Schema for the ibmlicensings API. Documentation
        For additional details regarding install parameters check: https://ibm.biz/icpfs39install.
        License By installing this product you accept the license terms https://ibm.biz/icpfs39license.'
      displayName: IBM License Service
      kind: IBMLicensing
      name: ibmlicensings.operator.ibm.com
      resources:
      - kind: Deployment
        name: ""
        version: v1
      - kind: Ingresses
        name: ""
        version: v1beta1
      - kind: Pod
        name: ""
        version: v1
      - kind: ReplicaSets
        name: ""
        version: v1
      - kind: Role
        name: ""
        version: v1
      - kind: RoleBinding
        name: ""
        version: v1
      - kind: Route
        name: ""
        version: v1
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      - kind: ServiceAccount
        name: ""
        version: v1
      - kind: configmaps
        name: ""
        version: v1
      - kind: ibmlicenseservicereporters
        name: ""
        version: v1alpha1
      - kind: ibmlicensingmetadatas
        name: ""
        version: v1alpha1
      - kind: ibmlicensings
        name: ""
        version: v1alpha1
      - kind: status
        name: ""
        version: v1alpha1
      specDescriptors:
      - description: Consider updating to enable chargeback feature
        displayName: Chargeback Enabled
        path: chargebackEnabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:checkbox
      - description: Chargeback data retention period in days. Default value is 62
          days.
        displayName: Chargeback Retention Period in days
        path: chargebackRetentionPeriod
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: 'Where should data be collected, options: metering, datacollector'
        displayName: Datasource
        path: datasource
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Environment variable setting
        displayName: Environment variable setting
        path: envVariable
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: Set additional features under this field
        displayName: Features
        path: features
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Enables https access at pod level, httpsCertsSource needed if
          true
        displayName: HTTPS Enable
        path: httpsEnable
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:checkbox
      - description: Should Ingress be created to expose IBM Licensing Service API?
        displayName: Ingress Enabled
        path: ingressEnabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: If ingress is enabled, you can set its parameters
        displayName: Ingress Options
        path: ingressOptions
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Additional annotations that should include f.e. ingress class
          if using not default ingress controller
        displayName: Annotations
        path: ingressOptions.annotations
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: If you use non-default host include it here
        displayName: Host
        path: ingressOptions.host
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Path after host where API will be available f.e. https://<hostname>:<port>/ibm-licensing-service-instance
        displayName: Path
        path: ingressOptions.path
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: TLS Options to enable secure connection
        displayName: TLS
        path: ingressOptions.tls
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Existing or to be created namespace where application will start.
          In case metering data collection is used, should be the same namespace as
          metering components
        displayName: Instance Namespace
        path: instanceNamespace
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Is Red Hat Marketplace enabled
        displayName: RHMP Enabled
        path: rhmpEnabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: Should Route be created to expose IBM Licensing Service API?
          (only on OpenShift cluster)
        displayName: Route Enabled
        path: routeEnabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:checkbox
      - description: If default SCC user ID fails, you can set runAsUser option to
          fix that
        displayName: Security Context
        path: securityContext
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Sender configuration, set if you have multi-cluster environment
          from which you collect data
        displayName: Sender
        path: sender
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Unique ID of reporting cluster
        displayName: Cluster ID
        path: sender.clusterID
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: What is the name of this reporting cluster in multi-cluster system.
          If not provided, CLUSTER_ID will be used as CLUSTER_NAME at Operand level
        displayName: Cluster Name
        path: sender.clusterName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: License Service Reporter authentication token, provided by secret
          that you need to create in instance namespace
        displayName: Reporter Secret Token
        path: sender.reporterSecretToken
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: URL for License Service Reporter receiver that collects and aggregate
          multi cluster licensing data.
        displayName: Reporter URL
        path: sender.reporterURL
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Usage Container Settings
        displayName: Usage Container Settings
        path: usageContainer
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: Should collect usage based metrics?
        displayName: Usage Enabled
        path: usageEnabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      version: v1alpha1
    - description: 'IBMLicensingMetadata is the schema for IBM License Service. Thanks
        to IBMLicensingMetadata, you can track the license usage of Virtual Processor
        Core (VPC) metric by Pods that are managed by automation, for which licensing
        annotations are not defined at the time of deployment, such as the open source
        OpenLiberty. / For more information, see documentation: https://ibm.biz/icpfs39install.
        License: By installing this product you accept the license terms. For more
        information about the license, see https://ibm.biz/icpfs39license.'
      displayName: IBMLicensing Metadata
      kind: IBMLicensingMetadata
      name: ibmlicensingmetadatas.operator.ibm.com
      version: v1alpha1
  description: "**Important:**\n- If you are using the IBM Licensing Operator as part
    of an IBM Cloud Pak, see the documentation for that IBM Cloud Pak to learn more
    about how to install and use the operator service. For the link to your IBM Cloud
    Pak documentation, see [IBM Cloud Paks that use Common Services](https://ibm.biz/cpcs_cloudpaks).\n-
    If you are using the IBM Cloud Platform Common Services, do not install the IBM
    Licensing Operator directly. Only install this operator using the IBM Common Services
    Operator. For more information about installing this operator and other Common
    Services operators, see [Installer documentation](https://ibm.biz/cpcs_opinstall).
    Additionally, you can exit this panel and navigate to the IBM Common Services
    tile in **OperatorHub** to learn more about the operator.\n- If you are using
    a stand-alone IBM Container Software, you can use the IBM Licensing Operator directly.
    For more information, see [ibm-licensing-operator for stand-alone IBM Containerized
    Software](https://github.com/IBM/ibm-licensing-operator#ibm-licensing-operator-for-stand-alone-ibm-containerized-software).\n\n**IBM
    Licensing Operator overview**\n\nIBM Licensing Operator installs License Service.
    You can use License Service to collect information about license usage of IBM
    Containerized products and IBM Cloud Paks per cluster. You can retrieve license
    usage data through a dedicated API call and generate an audit snapshot on demand.\n\n**Supported
    platforms**\n\nRed Hat OpenShift Container Platform 4.10 or newer installed on
    Linux x86_64, Linux on Power (ppc64le), Linux on IBM Z and LinuxONE.\n\n**Prerequisites**\n\nThe
    following prerequisites apply when you install License Service as a part of an
    IBM Cloud Pak or with IBM Cloud Platform Common Services.\n- For the list of operator
    dependencies, see the IBM Knowledge Center [Common Services dependencies documentation](https://ibm.biz/cpcs_opdependencies).
    The dependencies are automatically managed by Operant Deployment Lifecycle Manager.\n-
    For the list of prerequisites for installing the operator, see the IBM Knowledge
    Center [Preparing to install services documentation](https://ibm.biz/cpcs_opinstprereq).\n\n**Documentation**\n\n-
    If you are using the IBM Licensing Operator as part of an IBM Cloud Pak, see the
    documentation for that IBM Cloud Pak, for a list of IBM Cloud Paks, see [IBM Cloud
    Paks that use Common Services](https://ibm.biz/cpcs_cloudpaks). \n- If you are
    using the operator with an IBM Containerized Software:\n    - To install License
    Service as a part of the IBM Cloud Platform Common Services, see the Knowledge
    Center [Installer documentation](https://ibm.biz/cpcs_opinstall).\n    - To install
    License Service directly, click **Install** and create an **IBM Licensing** resource
    instance. For more information, see [ibm-licensing-operator for stand-alone IBM
    Containerized Software](https://ibm.biz/license_service4containers)."
  displayName: IBM Licensing
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAK8AAACvCAMAAAC8TH5HAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAB1UExURQAAAJGS77CC4pCS75yM64uV8pSQ7puA85OV87OB4auF5Hyd+H2c936b9n6b94Ca9n+b9n+b9n+b9qOJ56SI55yM6qSI536b96aH5q2D45mN64OZ9ZWQ7oyU8XWg+6uG5oqg/p6L6m+k/ZuY+3mr/6qQ9LqM80D8C0oAAAAbdFJOUwA67R4KKxMBBP6ak6vZgVtJxG5ot+hQ7YDVkwC2C58AAAuSSURBVHja7ZyJerK8EoCDCSTKjoiIS13of/+XeGYm4NLKrvj1OYxt7aa8TiazJZGxSSaZZJJJJvmcSCn/Eq7Cz79DLJk0rb+kXdM9nz0m/4p2mZufz3lAZvEn1HsGye2J9128h7/Gezj8Nd7D3+I9/xu8SjWHrS76bfN8A+NsYxjowCvbPN+QSGB6kWi6QHteyQLPfx+wYsH2eHSthgu05lXMy/PceRcwxtnjdnts4mjLq5hBceVdcVsya71FMeov0JIXMuQwR+DoXX5EMgf0uz2GrDYbb8mrmE+4Z/NdvDCApN+jX3uFdrySqfW70wzFbFLwWtVNkXa8ONlIvfx9Dk0xSyvYq0NpxasYJ9o8emcUVCw6EjGvuUpLXgfVm9cP1fAZp1yyCKeGBf8pB96g9jUZ57c6s1vIIAUfjXqY9eFg1yiuKJnOECzeW+TJm0+rxRGGWfcP7/dld8bZwqcp/dJqIs9hrJIJ/JD2abV5j1StfJn1/pofo/Kx0ae1KfAO7/Vld7anfVpf28M5kKPDc9kYLRW4RDhIwYV/PozVUAF39Qre3BmrvsM04nisjHHyJlUjZEOefuBj8UIA81zHfGJ84BYeHAP9LKseP1r5LNnvOlHeXJgqRZbUPzT97PHvBVb48VCX09W54du2u3ZJwjD0It/gqmCue/yoolm4b7tQjmohh7cGAWzHC8x/qOFOZmBG4bbERDkQrVYyiGP7iPwPLGrgsAofYbePonEJ2CHxAuvjxEjLvfUj7J1BaP0irY3i888SA63l3alWgwKjbXueZztOSBoucOE33huIZdsWHChXRds72O069PyHhSEBDiOynbAEBiGreCGJKoa5zT8GVBzt4QNgXc+wbq4YvW+hSMkDYNa4EYihWqlYtmouSsYTo4XvgWezHKDcI+7xuPbMMp7JH0GEfhZGRMDIG5FRtLG1IGCNvTp/d9nFZhMx/DXYH/cgSBv6SscM+Tyf0P450Lw+iCmbOGAMonOeO/XlMyTjgAsfmWAN9Y53RFy0hDAovXBDSBFBVAIHDdUJ2lre3J6AVG9Hcln5NQyKCUcrd390g5/BtjpNR2KNGwTVpRDSmk6et6jwCv0ScVhpxopxl3DBIjzVjrYk5gVuEPAaw7UP+aFV+0ex5Aq8y/hTYhiE/UXjhibrlBUisUm8hmHwqujuH3IqQLA/0dT+Af8Q34hT8du3QXlR4nrdkxhJ0554nwAXhpvj+hLUo2u/zWoJM1aXy70ZP8e97APWJ+WGbN1AXNP8tedAasM96PLu4Ik2jhpHZLkqgdGM5TNjuKzNnhkiUmneH8CSCe9wpXV429HDlCu7GcV9JwemWoEbWr3rGZx2iMs5F4+T3S1p89DoYGvkUeLCKC67m+uBsVwVuGpI+QVohGtZ6rHrU+Cu/UaP/ps4KY3iWhlipwNwd4Arh1WLCIy4lpA/2yiF4XZ9ehgMuaRgt7r6FMWiC9DuL64YWtyCrQKuEOLe1iJsG+eO2W8eo+POdrvVtdULrgG0Dbg76xW1uCDcm5GCguzDAeNlz0qPqgfzGunJeAl4aOug6KYQ7l2WhI7DZEMqZ7L5a1uBZWTQF3/QVHvmUosOBX0ZVkbfkgNtDYCbDcDVsIKbQYCJBCY/gak7FHQh+bqiX7LwsnuYfr1gqUTCUsPWgsWdF1H2I1/ZoYBMSLs3o3/blyke+FRiEPE9c1Huq9dpV60GWQNmvybSIrCnee0SGIlDJzJfVzwrttTq7bfkUNCSzV71a19pScNOGHrmi9pWV/Uue6lXYpEcBFfgslSOPG0MBTASc/YK3455PEqvyYY5r0G4AeH6gWHqSCyVxQ2s9ksJw9B/ATBYVUy8fdRL6ZhhlPo1HpIyHelM38OmCuA6oWvzwTah69DTbiW6qxdMCdPdAIGLbrC8lyIimxHRgrhQcA+cdoqluxXc0u7qhcTGNBAYeKkB9CTASfJjVuTo7mvoRsO676Ci+LRanVbd91YgLggp2GI1/kpRq7MAXnuDjBhC8Qpkl3UepwIXgblseDQq2XBcUK8bru0hGgbni7ynzrMNs1xOuJDmNQMAsfAI2B0CjOaAvKuuK2aES8C8XU8Sn98H9SKw12/SwfwVzNyArOLOL1lxEpO37/lKFujlpW3UfTSZwpxaQCkXb+JVd3OAAg1xrQ4vFGzC0MDrbuvLSGtRiSVYuonjeNU5MxMWAVudZzct1azdLmUXzGZLV7BCySxG6Zrq4MsFXqv79A7WiLu1OwwLFgElr7VA3LQjLtZnCCx7+KNo7a4BuG3lhRmKWXQ0LME40Gbxsqt6BQH3arExZ+viCl67Ib1rGHFLQPIQL7JFnHTjRfUCb68whR1mXM3dttpjcWvIAS6uNCRxlmVxxypeCVJw3wjl0/LzmrfaVG4kBgFT6ge57wJ4M7OTfmlNS4j+McpB4G2rTfBGkhAwp2UcWfB2cw/FFogBKQvxrhtTLMnMZYJiFG4eeLM0zVLRg3dIzmJvAbfRgiXjS81rXfeBLIE3TTuVQneZeH8Fb4HXFQ0rcGKJcsNFXsRdduYdViSQBQNy0LCilaSIu+R3TeqP8KKLQAXXzjgw3hR5l3erFvoldOOVr9Cv5eK6v1tzXch0UZfLNGEPvGQi3fU7tMi1m45PgCtb4Nin974Lftmd9yUtJZ94q/NgUG9KvA9rWOjgwKATMTqv3mpcbcDgQxaLRbpYyp+89/5tLMF98GTAVZsP4LfpAuXRYnALBwof+0AxejR0EVVpO4ARbvpz96D1GV7FvNoJB4lNDLiQOKofIQSTicQcnzeq5ZUsxTpi8ctQJeVrJmNj8wbEWxHhYNxjXff8UiT1vww1Oq9R59Dgz1gGb5Kff5a62jA/4tD222Ml75J4zd+8uglmfcQB76s2nktsM2w2z8p2yamWG90eTNrd9ly/ALnAtlP8LO5a1FdSo9sv7h3cVvGqGHkXT9Sr+3ZcjO4faNNYUMErkHf2tIeuqBNhjc0bHXEDoVHBa20qeRm1liw1Mq9H29z68Ard+hs7f0BzWD/3S8g7q+TV3RohR8VVLqq34pgR2G8NL9O8alx3Rrvy7Cr3q2LkXTyPClrBY55JgPqCthFGVbxsgbxxRd2jxKCGTS/zpelW0beD8pB4NxVhVw7t2HSvj0m9lfUx5A/zzWw2q0yPHzYHjWEOuDXvWLnhAtL1Gah3XrWsImkL/WjAkoX7au+r00bQ7my+qFr4ekETpFvyUGsOKOAgZrNNZaE2InCx9XF/qVmFQwNGBVevs42n31K9+5oqFxw0GURc22UayXjBenHrY1Z7UJ/FpOCkRsFjWe+SNsLuef2xCm0QMfvwe60pxnGf5v7iNTR/xWZWb8GjWcOFgBtK3FLBM+uTCpatd5aigue1Pngs4yVcp8VphmT+YYuQGIhxm/Fu37w+j0mPBk4+BIy4ett8q52lGJTneJsbHwHGwx/FQYp2Q6wtogCWH8DNLtdt0S1Pi6RICx8JG1nFCluOV9yWLgrrjAI4HfVQNtYu5emw9ri0EyZGWpCNORYxvVuAGZeHgLIuEVZB5UnAqGLryfsLvDx31Gfa6czSSW+D7XRFVZgEyizlRfEm3yJFSaiM+HQ5Ee5ll3SNVgCczkvi+SJ5c+PMMtIV0BLu6RL32P8Lry8pcVHJcZoYlniDcCNJ49Xp+/uk5QK20PP0kLWYP8qsg2zuvl/VyAlQS1bQ7SnjfQ814O7WeF4jX/P/5l//fT2V77svePeNd/gFNam/FN/eZPd9io0B/ojOwMWVsA8/wO1RZvc/nOgTbqfi7okAfDbUe+KDjcVsPq9X81eJPK/g/So476kfWUG1S6vjmcIqYpGkGwT7r4t8FfffdIP7ajmdNlnC2Qto2fWNtixjudRr4a+VLF0uTa4vJF8XKuXbg/Hr33TjffKn3gp/kkkmmWSSSSaZZJJJJplkkkkmmWSS/yf5H6HANgUotAMHAAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - IBMLicensing
  - IBM
  - Cloud
  - License
  - Service
  - License Service
  labels:
    name: ibm-licensing-operator
  links:
  - name: GitHub
    url: https://github.com/IBM/ibm-licensing-operator
  maintainers:
  - email: talk2sam@us.ibm.com
    name: talk2sam
  maturity: alpha
  provider:
    name: IBM
  relatedImages:
  - image: icr.io/cpopen/ibm-licensing-operator:1.20.12
    name: IBM_LICENSING_OPERATOR_IMAGE
  - image: icr.io/cpopen/cpfs/ibm-licensing:1.20.12
    name: IBM_LICENSING_IMAGE
  - image: icr.io/cpopen/cpfs/ibm-license-service-reporter-ui:1.20.12
    name: IBM_LICENSE_SERVICE_REPORTER_UI_IMAGE
  - image: icr.io/cpopen/cpfs/ibm-postgresql:1.20.12
    name: IBM_POSTGRESQL_IMAGE
  - image: icr.io/cpopen/cpfs/ibm-license-service-reporter:1.20.12
    name: IBM_LICENSE_SERVICE_REPORTER_IMAGE
  - image: icr.io/cpopen/cpfs/ibm-licensing-usage:1.20.12
    name: IBM_LICENSING_USAGE_IMAGE
  version: 0.0.0
