apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicensing
metadata:
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
  name: instance
spec:
  version: 4.2.12
  apiSecretToken: ibm-licensing-token
  datasource: datacollector
  httpsEnable: true
