apiVersion: v2
name: ibm-license-service-scanner
description: A Helm chart for IBM License Service Scanner ArgoCD installation
type: application
<<<<<<< HEAD
version: 4.2.19
=======
version: 4.2.18
>>>>>>> latest-4.x
