apiVersion: v2
name: ibm-license-service-reporter
description: A Helm chart for IBM License Service Reporter ArgoCD installation
type: application
<<<<<<< HEAD
version: 4.2.19
=======
version: 4.2.18
>>>>>>> latest-4.x
