global:
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key
  licenseAccept: true

ibmLicenseServiceReporter:
  namespace: ibm-ls-reporter
  imageRegistryNamespaceOperator: cpopen
  imageRegistryNamespaceOperand: cpopen/cpfs
  spec:
    authentication:
      useradmin:
        enabled: true
<<<<<<< HEAD
    version: 4.2.19
=======
    version: 4.2.18
>>>>>>> latest-4.x
